### ISSUE TITLE
The workspaces location in the status bar sometimes loads "left" instead of always being in bottom right

### ISSUE THREAD

**Issue by GitMurf** [nothingislost/obsidian-workspaces-plus#13]
![image](https://user-images.githubusercontent.com/64155612/132878728-1e9c4ef9-cbb0-4641-a875-6820654a9781.png)

**Comment by nothingislost** [comment]
Fixed in the upcoming release (0.0.7)

**Comment by nothingislost** [comment]
I don't think this is actually fixed. Need to think of a better way to handle this. Not everyone can be in the bottom right of the status bar. Someone could come in and try to put their plugin in the bottom right as well but I can at least try and get into the bottom right given a default setup.

**Comment by GitMurf** [comment]
For me it has been working fine with the fix you made. But yeah I see what you mean. No more issue from my end so feel free to close at your discretion pending your comments above.

**Comment by jsmorabito** [comment]
this occurred for me after creating a new workspace with the picker on a test database with no prior workspaces created

<img width="398" alt="image" src="https://user-images.githubusercontent.com/46250921/133288263-bafc9de0-5ee0-430a-8604-9aff82515a7f.png">

**Comment by jsmorabito** [comment]
closing for now, so far so good in 0.1.4!
