### ISSUE TITLE
[Feature] Add a cursor hover change on the Edit workspace name icons

### ISSUE THREAD

**Issue by GitMurf** [nothingislost/obsidian-workspaces-plus#15]
It doesn't seem natural that you can click the little edit button to rename when the cursor on hover is the default pointer. I would maybe change it to the "I" (capital i looking text editor cursor) or something like that. But it should be different than the default click hover pointer finger as that is what shows when you hover over any of the workspace items themselves in the list.

![image](https://user-images.githubusercontent.com/64155612/132890839-a3d5f1ac-c398-43dc-8c77-fd7a44961ff8.png)

**Comment by nothingislost** [comment]
This is fixed right? I see a pointer when hovering the pencil, a hand when selecting an item, and a cursor when renaming

**Comment by GitMurf** [comment]
I meant I didn’t want to see the default pointer when hovering the pencil. It should change to something that isn’t the same arrow pointer as default OS when you are hovering non clickable stuff. Should change to something to show you can click it so if you hover to the right of the item it changes to the default pointer when outside of your workspace modal. So basically I can see a change from pencil hover to hover outside the workspace modal.

**Comment by jsmorabito** [comment]
this is from Todoist: 
![image](https://user-images.githubusercontent.com/46250921/132913539-371f2fbb-9048-43bc-85e9-02469b6d9d3e.png)

Theres a highlight on the icon you're hovering over and the click hand is always active

**Comment by jsmorabito** [comment]
closed via release 0.1.0
