### ISSUE TITLE
Workspace icon not vertically centered in status bar

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#22]
![image](https://user-images.githubusercontent.com/46250921/132949529-3c4b65ec-ac21-4118-9cb4-250dc240c305.png)

**Comment by jsmorabito** [comment]
weird I'm trying to recreate this problem in a test vault and with other themes and I'm unable to 🤔

**Comment by nothingislost** [comment]
yeah, it's very hard to get that icon to align properly across different themes as everyone is doing slightly different to the status bar styling. I moved on from trying to get it perfect as it was taking too long but I'll revisit this eventually

**Comment by jsmorabito** [comment]
what's strange is that its working with the same theme (Yin and Yang) in my test database
<img width="181" alt="image" src="https://user-images.githubusercontent.com/46250921/132959450-66df9d17-720d-4223-9fb7-89cc447957fb.png">

I might be having some personal problem?

**Comment by nothingislost** [comment]
Yeah, I can't replicate this. Is this still a problem?
![image](https://user-images.githubusercontent.com/89109712/134060265-6a051e5d-8f18-4c0c-8b81-4353395a589c.png)

**Comment by jsmorabito** [comment]
![image](https://user-images.githubusercontent.com/46250921/134061027-eb0f1ab0-510c-41e5-8e52-7f79289224c0.png)

yea :/ maybe something from inspector might have a clue?

![image](https://user-images.githubusercontent.com/46250921/134061388-89766201-3b7a-49d1-8d04-72fb569df297.png)

![image](https://user-images.githubusercontent.com/46250921/134061458-5f168d0f-4871-4c11-9256-e1bb8d85bf28.png)

**Comment by nothingislost** [comment]
haha, so Yin&Yang fixed this for us. I'm guessing you need to update your theme. Go into the the theme browser and click on "use" for Yin&Yang which will pull down the latest version. Here's what she did:

![image](https://user-images.githubusercontent.com/89109712/134065470-1ffcd7e9-550b-4df9-91a5-53738e7a8800.png)

**Comment by nothingislost** [comment]
Note that she changed the rename and delete icons as well before you ask why I changed them :)

**Comment by jsmorabito** [comment]
to update a theme you press 'use' !? 😵

...

it worked 😂

**Comment by nothingislost** [comment]
Yeah, theme updating is not well implemented at the moment. I just go in every couple days and "use" my current theme to make sure I have the latest.

I've stole her alignment styling and it'll be in the next release.
