### ISSUE TITLE
Active workspace checkmark bug on window resize

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#31]
https://user-images.githubusercontent.com/46250921/133012395-62ef54ac-a53a-478a-97a8-028e476d6885.mov

**Comment by nothingislost** [comment]
This seems consistent with the existing obsidian modals except for the fact that they don't show an active element in any of the native modals. I think automatically scrolling the list to keep it on the bottom where the active check mark is, is more confusing than the existing behavior but feel free to propose a solution for what it should look like.

**Comment by nothingislost** [comment]
Also, why are you resizing a window with a modal open? Come on :)

**Comment by jsmorabito** [comment]
> Also, why are you resizing a window with a modal open? Come on :)

I actually noticed it when I moved the obsidian from a larger monitor to a smaller monitor and it automatically changed the window size. I resized the window to reproduce. You're right I don't think normal people resize windows with modals open haha

not sure I understand what you mean by this "I think automatically scrolling the list to keep it on the bottom where the active check mark is, is more confusing than the existing behavior but feel free to propose a solution for what it should look like."

I'm referring to the check mark being on the wrong z-axis layer if that makes sense.

**Comment by nothingislost** [comment]
Ah, it was hard to see that the checkmark was the highlight of that video. It's resolved in the latest release.

**Comment by nothingislost** [comment]
@jsmorabito can we close this?

**Comment by jsmorabito** [comment]
fixed in 0.1.3
