### ISSUE TITLE
Add "Workspace Picker" tooltip for status bar workspace picker button

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#32]
![image](https://user-images.githubusercontent.com/46250921/132998066-f33001da-c798-487f-9e49-df682fcdd619.png)

**Comment by nothingislost** [comment]
I'm not a fan of the visual noise but no problem making it an option

**Comment by jsmorabito** [comment]
> I'm not a fan of the visual noise but no problem making it an option

Yeah I agree...some may find it helpful with discoverability but could be unnecessary noise for veteran workspace pickers like ourselves 😤 

toggle would be sweet!

**Comment by jsmorabito** [comment]
added in a recent update
