### ISSUE TITLE
Workspace Picker modal

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#34]
Open the full size picker modal (instructions on) with assignable hotkey independent of whether instructions are toggled on for workspace picker activated from status bar

**Comment by nothingislost** [comment]
Should there even be a hotkey to open the quick switcher in the bottom right? If you're using a hotkey, it seems like the modal should always be in the top middle.

**Comment by jsmorabito** [comment]
> Should there even be a hotkey to open the quick switcher in the bottom right? If you're using a hotkey, it seems like the modal should always be in the top middle.

No, it won't be necessary to have a hotkey for the quick switcher in the bottom right

**Comment by jsmorabito** [comment]
added in recent update
