### ISSUE TITLE
Where is main.js?

### ISSUE THREAD

**Issue by kmaustral** [nothingislost/obsidian-workspaces-plus#39]
This looks great, but I can't find main.js to instal the plug-in.

Thanks.

**Comment by jsmorabito** [comment]
Download the zip from https://github.com/nothingislost/obsidian-workspaces-plus/releases/tag/0.1.2 and it should be in there

**Comment by kmaustral** [comment]
Thanks. It works well so far. I hope I can offer some useful feedback.

**Comment by jsmorabito** [comment]
> Thanks. It works well so far. I hope I can offer some useful feedback.

great! all feedback is welcome :)
