### ISSUE TITLE
Cool Bug (cmd-z duplication in switcher)

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#40]
**Describe the bug**
Cmd-z duplicates workspaces after creating a new one; however, they do not remain after closing and reopening the picker

**To Reproduce**
1. Create a workspace with the picker or modal
2. open picker (this bug does not occur with modal)
3. Press `cmd-z` a couple times
4. Observe duplicates

**Expected behavior**
Not this 😂

https://user-images.githubusercontent.com/46250921/133539085-a83b588e-d432-466f-a976-9808bb677365.mov

**Comment by nothingislost** [comment]
Stop doing weird stuff :)

I can replicate this and am looking into how to address it properly.

**Comment by jsmorabito** [comment]
fixed in 0.1.3
