### ISSUE TITLE
Navigation out of input field during edit state

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#46]
**Describe the bug**
User is able to navigate through workspace list while in edit mode

https://user-images.githubusercontent.com/46250921/133851332-e6e6502a-e3f8-4cbf-8e3d-beffd9833dd1.mov

**To Reproduce**
1. go to edit mode
2. press up or down arrow
3. observe edit mode still active while other workspaces can be selected

**Expected behavior**
The native behavior of up and down arrow in input field is to go to the beginning and end of the field 

https://user-images.githubusercontent.com/46250921/133851956-8417fd9d-90eb-4b43-b26c-99984c809648.mov

**Comment by nothingislost** [comment]
@jsmorabito is this resolved now?

**Comment by jsmorabito** [comment]
> @jsmorabito is this resolved now?

Yup! I'll leave it up to you if you want to add the up and down arrow to move the caret/insertion point behavior. its a nice to have but not a priority
