### ISSUE TITLE
Arrow key navigation not activating scroll to see overflowed content

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#49]
**Describe the bug**
Arrow key navigation not activating scroll to see overflowed content

**To Reproduce**
1. Resize window or have many workspaces in list so overflow is activated
2. scroll with arrow keys

**Expected behavior**
overflowed items to be shown

https://user-images.githubusercontent.com/46250921/134022488-1419ac1d-9b6e-4341-bdc4-281f5e06d4c5.mov

**Additional Context**
This occurs for both the modal and quick picker. Mouse wheel scroll does work.

**Comment by jsmorabito** [comment]
This is fixed, but I'm noticing a jarring jump in the scrolling that I don't think should be there. notice the jump when I switch from the Obsidian design workspace

https://user-images.githubusercontent.com/46250921/134097705-e8dc6f9d-19ef-46de-8e37-cb27ed6bb2d7.mov

For comparison here is the command menu:



https://user-images.githubusercontent.com/46250921/134098014-9b218aa8-00ad-469f-b53e-4867d90a8722.mov

**Comment by nothingislost** [comment]
Addressed in 0.2.0
