### ISSUE TITLE
Console error when doing Shift + Enter to save as new workspace name

### ISSUE THREAD

**Issue by GitMurf** [nothingislost/obsidian-workspaces-plus#5]
I typed "TESTING" into the modal without having a workspace called that and pressed Shift + Enter and it gave this console error.

![image](https://user-images.githubusercontent.com/64155612/132595345-8ba8dba4-71e7-4dfc-8fb9-a903268e9b46.png)

**Comment by GitMurf** [comment]
Using v0.0.2

**Comment by GitMurf** [comment]
Now that I look at this, it may have nothing to do with your plugin and instead have to do with the native Obsidian workspaces and issues they may have with sliding panes?

**Comment by nothingislost** [comment]
Hmmm, can't replicate it, even with sliding panes. Let me know if it's still an issue on 0.0.3 and if so, how to replicate.

**Comment by GitMurf** [comment]
I'm working on it. Disabling one plugin at a time ;-p I think it was a plugin which don't play nicely if proper "state" validation/tracking isn't in place. Since Workspace changes trigger a whole new layout, I assume it is a plugin that depends on the initial load/layout of obsidian. I'll see what the culprit is and let you know.

**Comment by nothingislost** [comment]
Does it happen only on shift+enter? Shift+enter saves the current workspace as the selected item or whatever string has been typed into the input box. Once saved, it'll load that same workspace, triggering a layout change.

**Comment by nothingislost** [comment]
Are we good to close this @GitMurf ?
