### ISSUE TITLE
workspace with empty pane no longer displaying empty pane

### ISSUE THREAD

**Issue by erikjwells** [nothingislost/obsidian-workspaces-plus#54]
as of the last plugin update, my workspaces are no longer showing empty panes - but rather deleting them altogether.
I have workspaces that leave the center pane empty - at the add new file entry point. This allows me to quickly begin a new note in the center of my space and have all my supporting panes intact on the sides. 

Now the center pane is deleted and the workspace is unusable unless I recreate it from scratch.

**Desktop 
 - OS: MAC OS BigSur 11.6
 - Browser: Firefox 
 - Version: 93.0 64bit

**Obsidian version
v0.12.19

What saved workspace looks like initially

<img width="2508" alt="Screen Shot 2021-10-20 at 10 31 43 AM" src="https://user-images.githubusercontent.com/15148924/138113788-af96bed7-c793-45a7-b82f-f0adc6932981.png">

What workspace looks like after reloaded.

<img width="2509" alt="Screen Shot 2021-10-20 at 10 32 16 AM" src="https://user-images.githubusercontent.com/15148924/138114030-00d4e51e-c302-40bd-b5a8-822f402e1e1f.png">

**Comment by jsmorabito** [comment]
@erikjwells thank you for sharing. I've replicated this behavior. If it was working before one of the updates I imagine it's something we can add back in. handing over to @nothingislost 🦾

**Comment by jsmorabito** [comment]
@erikjwells empty workspaces were added back in an insider build so you will be able to use them again soon if they haven't already been released in a public update
