### ISSUE TITLE
Obsidian update killed workspaces plus?

### ISSUE THREAD

**Issue by LouisLeWild** [nothingislost/obsidian-workspaces-plus#87]
**Describe the bug**
Can't open workspaces. Icon appears in status bar, no reaction when clicking icon in status bar.

**To Reproduce**
1. Go to status bar
2. Click on Workspaces plus icon

**Expected behavior**
Workspaces plus menu appears

**Desktop (please complete the following information):**
 - OS: Windows

**Obsidian version:**
Obsidian version 1.0.0

**Additional context**
Below is from the release notes of Obsidian 1.0.0

> Workspace information is no longer saved to the .obsidian/workspace file. It is now saved to workspace.json.

wondering if your plugin is still looking in the .obsidian/workspace file for workspace info.

**Comment by jowibou** [comment]
Same on MacOS

**Comment by sutrisno00** [comment]
Same on MacOS. And loading of workspace plus (using the command-P) is not working as well. Could be related issue

**Comment by mmdzt** [comment]
Hope workspace plus can be updated, I love it very much. Thanks for getting this done.

**Comment by tprotopopescu** [comment]
Same on linux. I feel paralyzed without this :)

**Comment by zen010101** [comment]
Only use Ctrl-P to load the Workspaces list

**Comment by hustrjh** [comment]
@mmdzt @HyperEpsilon I found a solution. Inside [Blue-topaz-examples](https://github.com/cumany/Blue-topaz-examples/releases/tag/20221021), the author fixed the problem. Just download the vault, replace the plugin and wait for @nothingislost. I hope that will help. :smile:

**Comment by sutrisno00** [comment]
> @mmdzt @HyperEpsilon I found a solution. Inside [Blue-topaz-examples](https://github.com/cumany/Blue-topaz-examples/releases/tag/20221021), the author fixed the problem. Just download the vault, replace the plugin and wait for @nothingislost. I hope that will help. 😄
> Tips: Don't overwrite your own data file.

Wow - this works, many many thanks.

**Comment by Celeblith** [comment]
Same problem here. I check for updates every day in the hopes that I'll get my old workflow back. For now, a save-and-switch hotkey for the base plugin is holding me over. I recommend everyone use that until Workspaces Plus gets fixed.

**Comment by hustrjh** [comment]
Hi,@Celeblith. The link I recommended includes `workspaces plus` plugin which modified by the author of the example vault. That plugin isn't intend to replace the original one but help people who need the function for now. It is still the plugin we used before which gets some bugs fixed. So it's free to update if nothingislost updates the plugin later.

**Comment by jsmorabito** [comment]
Hi everyone, I merged fixes for the general and beta releases. Hopefully it is working for you all now. Please see #93 for and update on the development status of workspaces plus. If you are still running into issues feel free to post them but understand that NIL is not currently available to maintain the plugin.

**Comment by hustrjh** [comment]
@jsmorabito Thanks for your work. It works well! :heart:
